CREATE TABLE RoomAddOn (
	
	RoomID INT NOT NULL,
	AddOnID INT NOT NULL,
	CONSTRAINT PK_RoomAddOnID
		PRIMARY KEY (RoomID, AddOnID),
	CONSTRAINT FK_Room_RoomAddOn
		FOREIGN KEY (RoomID) 
		REFERENCES Room(RoomID),
	CONSTRAINT FK_Amenity_RoomAddOn
		FOREIGN KEY (AddOnID) 
		REFERENCES AddOn(AddOnID),
)
GO